# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Data Only Greater
tagline:          Everything Mathew Topper...
url:              http://www.dataonlygreater.com
paginate:         1
baseurl:          /
author:
  name:           Mathew Topper
  url:            https://twitter.com/H0R5E
  email:          damm_horse@yahoo.co.uk

# Custom vars
version:          0.0.1
github:
  repo:           https://github.com/H0R5E/data-only-greater
