# Dependencies
markdown:         kramdown
highlighter:      pygments
gems:             [octopress-paginate, jekyll-archives, jekyll-last-modified-at, jekyll-sitemap]

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Data only Greater
tagline:          Mathew Topper's website
description:      "Welcome to Mathew Topper's fabulous internet experience."
tags:             [Software, Research, Life]
url:              http://www.dataonlygreater.com
baseurl:          ""

author:
  name:           Mathew Topper
  url:            https://twitter.com/H0R5E
  email:          damm_horse@yahoo.co.uk

pagination:
  limit:          false
  per_page:       3
  title_suffix:   " (page :num)"

jekyll-archives:
  enabled:
    - year
    - tags
  permalinks:
    year:         'archive/:year/'
    tag:          'archive/tag/:name/'
  layouts:
    year:         archive-year
    tag:          archive-tag

# Custom vars
version:          0.1.0
github:
  repo:           https://github.com/H0R5E/data-only-greater
twitter:
  username:       H0R5E
  userid:         142661495
  
# Include exclude files:
include:          [.htaccess]
exclude:          [COPYRIGHT.md, LICENSE_Poole.md, README.md]

