# Dependencies
markdown:         kramdown
highlighter:      pygments
gems:             [jekyll-archives, jekyll-paginate-v2, jekyll-sitemap]

# Permalinks
permalink:        pretty

# Setup
title:            Data only Greater
tagline:          Mathew Topper's website
description:      "Welcome to Mathew Topper's excellent internet adventure."
tags:             [Software, Research, Life]
url:              http://www.dataonlygreater.com
baseurl:          ""

author:
  name:           Mathew Topper
  url:            https://twitter.com/H0R5E
  email:          damm_horse@yahoo.co.uk

pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

jekyll-archives:
  enabled:
    - year
    - tags
  permalinks:
    year:         'archive/:year/'
    tag:          'archive/tag/:name/'
  layouts:
    year:         archive-year
    tag:          archive-tag

# Custom vars
version:          0.1.0
github:
  repo:           https://github.com/H0R5E/data-only-greater
twitter:
  username:       H0R5E
  userid:         142661495
  
# Include exclude files:
include:          [.htaccess]
exclude:          [COPYRIGHT.md, LICENSE_Poole.md, README.md]

